# pubspec.yaml (root)
name: flutter_pef_monit
description: A comprehensive performance monitoring library for Flutter applications. Track FPS, memory, CPU usage and more in real-time.
version: 1.0.0
homepage: https://github.com/hieudevs/flutter_pef_monit
repository: https://github.com/hieudevs/flutter_pef_monit
issue_tracker: https://github.com/hieudevs/flutter_pef_monit/issues
documentation: https://github.com/hieudevs/flutter_pef_monit#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # System information
  system_info2: ^4.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true